--========================================================================================================================
--========================================================================================================================
        INSERT OR REPLACE INTO LocalizedText
			(Tag,	Language,	Text)
		VALUES
			('LOC_OPTIONS_GROUP_TBQ_CHOOSE_STARTING_LAYERS',		'en_US',	"Choose Starting Layers Mod"),
			('LOC_OPTIONS_GROUP_TBQ_CHOOSE_STARTING_LAYERS',		'de_DE',	"Wähle Startschichten Mod"),
			('LOC_OPTIONS_GROUP_TBQ_CHOOSE_STARTING_LAYERS',		'es_ES',	"Elegir Capas Iniciales Mod"),
			('LOC_OPTIONS_GROUP_TBQ_CHOOSE_STARTING_LAYERS',		'fr_FR',	"Choisir les Couches de Départ Mod"),
			('LOC_OPTIONS_GROUP_TBQ_CHOOSE_STARTING_LAYERS',		'it_IT',	"Scegli i Livelli Iniziali Mod"),
			('LOC_OPTIONS_GROUP_TBQ_CHOOSE_STARTING_LAYERS',		'ja_JP',	"開始レイヤーモッドを選択"),
			('LOC_OPTIONS_GROUP_TBQ_CHOOSE_STARTING_LAYERS',		'ko_KR',	"시작 레이어 선택 모드"),
			('LOC_OPTIONS_GROUP_TBQ_CHOOSE_STARTING_LAYERS',		'pl_PL',	"Wybierz Warstwy Startowe Mod"),
			('LOC_OPTIONS_GROUP_TBQ_CHOOSE_STARTING_LAYERS',		'pt_BR',	"Escolher Camadas Iniciais Mod"),
			('LOC_OPTIONS_GROUP_TBQ_CHOOSE_STARTING_LAYERS',		'ru_RU',	"Выбрать Начальные Слои Mod"),
			('LOC_OPTIONS_GROUP_TBQ_CHOOSE_STARTING_LAYERS',		'zh_Hans_CN',	"选择起始图层 Mod"),
			('LOC_OPTIONS_GROUP_TBQ_CHOOSE_STARTING_LAYERS',		'zh_Hant_HK',	"選擇起始圖層 Mod"),

			('LOC_MOD_CSL_SHOW_HEXGRID_ON_LOAD_OPTION',		'en_US',	"Show the hexgrid on game load"),
			('LOC_MOD_CSL_SHOW_HEXGRID_ON_LOAD_OPTION',		'de_DE',	"Hexgitter beim Laden anzeigen"),
			('LOC_MOD_CSL_SHOW_HEXGRID_ON_LOAD_OPTION',		'es_ES',	"Mostrar la cuadrícula hexagonal al cargar"),
			('LOC_MOD_CSL_SHOW_HEXGRID_ON_LOAD_OPTION',		'fr_FR',	"Afficher la grille hexagonale au chargement"),
			('LOC_MOD_CSL_SHOW_HEXGRID_ON_LOAD_OPTION',		'it_IT',	"Mostra la griglia esagonale all'avvio"),
			('LOC_MOD_CSL_SHOW_HEXGRID_ON_LOAD_OPTION',		'ja_JP',	"ゲーム読み込み時にヘックスグリッドを表示"),
			('LOC_MOD_CSL_SHOW_HEXGRID_ON_LOAD_OPTION',		'ko_KR',	"게임 로드 시 헥스그리드 표시"),
			('LOC_MOD_CSL_SHOW_HEXGRID_ON_LOAD_OPTION',		'pl_PL',	"Pokaż siatkę heksagonalną przy ładowaniu gry"),
			('LOC_MOD_CSL_SHOW_HEXGRID_ON_LOAD_OPTION',		'pt_BR',	"Mostrar grade hexagonal ao carregar o jogo"),
			('LOC_MOD_CSL_SHOW_HEXGRID_ON_LOAD_OPTION',		'ru_RU',	"Показать гексагональную сетку при загрузке"),
			('LOC_MOD_CSL_SHOW_HEXGRID_ON_LOAD_OPTION',		'zh_Hans_CN',	"游戏加载时显示六边形网格"),
			('LOC_MOD_CSL_SHOW_HEXGRID_ON_LOAD_OPTION',		'zh_Hant_HK',	"遊戲加載時顯示六邊形網格"),

            ('LOC_MOD_CSL_SHOW_HEXGRID_ON_LOAD_OPTION_DESC',		'en_US',	"Show the hexgrid layer when the game loads. Layers can still be toggled with the minimap filters or hotkeys."),
			('LOC_MOD_CSL_SHOW_HEXGRID_ON_LOAD_OPTION_DESC',		'de_DE',	"Hexgitter beim Laden anzeigen. Ebenen können weiterhin mit den Minikartenfiltern oder Tastenkombinationen umgeschaltet werden."),
			('LOC_MOD_CSL_SHOW_HEXGRID_ON_LOAD_OPTION_DESC',		'es_ES',	"Mostrar la cuadrícula hexagonal al cargar el juego. Las capas aún pueden alternarse con los filtros del minimapa o los atajos de teclado."),
			('LOC_MOD_CSL_SHOW_HEXGRID_ON_LOAD_OPTION_DESC',		'fr_FR',	"Afficher la grille hexagonale au chargement du jeu. Les couches peuvent toujours être activées avec les filtres de la mini-carte ou les raccourcis clavier."),
			('LOC_MOD_CSL_SHOW_HEXGRID_ON_LOAD_OPTION_DESC',		'it_IT',	"Mostra la griglia esagonale all'avvio del gioco. Gli strati possono ancora essere attivati con i filtri della minimappa o le scorciatoie da tastiera."),
			('LOC_MOD_CSL_SHOW_HEXGRID_ON_LOAD_OPTION_DESC',		'ja_JP',	"ゲーム読み込み時にヘックスグリッドを表示。レイヤーはミニマップフィルターやホットキーで切り替え可能。"),
			('LOC_MOD_CSL_SHOW_HEXGRID_ON_LOAD_OPTION_DESC',		'ko_KR',	"게임 로드 시 헥스그리드 레이어를 표시합니다. 레이어는 미니맵 필터나 단축키로 전환할 수 있습니다."),
			('LOC_MOD_CSL_SHOW_HEXGRID_ON_LOAD_OPTION_DESC',		'pl_PL',	"Pokaż warstwę siatki heksagonalnej podczas ładowania gry. Warstwy można nadal przełączać za pomocą filtrów minimapy lub skrótów klawiszowych."),
			('LOC_MOD_CSL_SHOW_HEXGRID_ON_LOAD_OPTION_DESC',		'pt_BR',	"Mostrar a camada da grade hexagonal ao carregar o jogo. As camadas ainda podem ser alternadas com os filtros do minimapa ou atalhos."),
			('LOC_MOD_CSL_SHOW_HEXGRID_ON_LOAD_OPTION_DESC',		'ru_RU',	"Показывать слой гексагональной сетки при загрузке игры. Слои можно переключать с помощью фильтров миникарты или горячих клавиш."),
			('LOC_MOD_CSL_SHOW_HEXGRID_ON_LOAD_OPTION_DESC',		'zh_Hans_CN',	"游戏加载时显示六边形网格层。仍可使用小地图过滤器或快捷键切换图层。"),
			('LOC_MOD_CSL_SHOW_HEXGRID_ON_LOAD_OPTION_DESC',		'zh_Hant_HK',	"遊戲加載時顯示六邊形網格層。仍可使用小地圖過濾器或快捷鍵切換圖層。"),

            ('LOC_MOD_CSL_SHOW_YIELDS_ON_LOAD_OPTION', 'en_US', "Show tile yields on game load"),
			('LOC_MOD_CSL_SHOW_YIELDS_ON_LOAD_OPTION', 'de_DE', "Kachel-Erträge beim Laden des Spiels anzeigen"),
			('LOC_MOD_CSL_SHOW_YIELDS_ON_LOAD_OPTION', 'es_ES', "Mostrar los rendimientos de losetas al cargar el juego"),
			('LOC_MOD_CSL_SHOW_YIELDS_ON_LOAD_OPTION', 'fr_FR', "Afficher les rendements des tuiles au chargement du jeu"),
			('LOC_MOD_CSL_SHOW_YIELDS_ON_LOAD_OPTION', 'it_IT', "Mostra i rendimenti delle tessere all'avvio del gioco"),
			('LOC_MOD_CSL_SHOW_YIELDS_ON_LOAD_OPTION', 'ja_JP', "ゲームのロード時にタイル収益を表示"),
			('LOC_MOD_CSL_SHOW_YIELDS_ON_LOAD_OPTION', 'ko_KR', "게임 로드 시 타일 수익 표시"),
			('LOC_MOD_CSL_SHOW_YIELDS_ON_LOAD_OPTION', 'pl_PL', "Pokaż dochody z pól przy wczytywaniu gry"),
			('LOC_MOD_CSL_SHOW_YIELDS_ON_LOAD_OPTION', 'pt_BR', "Mostrar os rendimentos dos terrenos ao carregar o jogo"),
			('LOC_MOD_CSL_SHOW_YIELDS_ON_LOAD_OPTION', 'ru_RU', "Показывать доходность клеток при загрузке игры"),
			('LOC_MOD_CSL_SHOW_YIELDS_ON_LOAD_OPTION', 'zh_Hans_CN', "游戏加载时显示单元格收益"),
			('LOC_MOD_CSL_SHOW_YIELDS_ON_LOAD_OPTION', 'zh_Hant_HK', "遊戲加載時顯示單元格收益"),

			('LOC_MOD_CSL_SHOW_YIELDS_ON_LOAD_OPTION_DESC', 'en_US', "Show the tile yields layer when the game loads. Layers can still be toggled with the minimap filters or hotkeys."),
			('LOC_MOD_CSL_SHOW_YIELDS_ON_LOAD_OPTION_DESC', 'de_DE', "Zeige die Ertragsschicht der Kacheln beim Laden des Spiels an. Ebenen können weiterhin mit den Minikartenfiltern oder Hotkeys umgeschaltet werden."),
			('LOC_MOD_CSL_SHOW_YIELDS_ON_LOAD_OPTION_DESC', 'es_ES', "Muestra la capa de rendimientos de losetas al cargar el juego. Las capas aún se pueden alternar con los filtros del minimapa o atajos de teclado."),
			('LOC_MOD_CSL_SHOW_YIELDS_ON_LOAD_OPTION_DESC', 'fr_FR', "Affiche la couche des rendements des tuiles lors du chargement du jeu. Les couches peuvent toujours être activées avec les filtres de la mini-carte ou les raccourcis clavier."),
			('LOC_MOD_CSL_SHOW_YIELDS_ON_LOAD_OPTION_DESC', 'it_IT', "Mostra lo strato dei rendimenti delle tessere all'avvio del gioco. Gli strati possono ancora essere attivati con i filtri della minimappa o i tasti di scelta rapida."),
			('LOC_MOD_CSL_SHOW_YIELDS_ON_LOAD_OPTION_DESC', 'ja_JP', "ゲームのロード時にタイル収益レイヤーを表示します。レイヤーはミニマップフィルターまたはホットキーで切り替えることができます。"),
			('LOC_MOD_CSL_SHOW_YIELDS_ON_LOAD_OPTION_DESC', 'ko_KR', "게임 로드 시 타일 수익 레이어를 표시합니다. 레이어는 미니맵 필터 또는 단축키를 사용하여 전환할 수 있습니다."),
			('LOC_MOD_CSL_SHOW_YIELDS_ON_LOAD_OPTION_DESC', 'pl_PL', "Pokaż warstwę dochodów z pól przy wczytywaniu gry. Warstwy można nadal przełączać za pomocą filtrów minimapy lub skrótów klawiszowych."),
			('LOC_MOD_CSL_SHOW_YIELDS_ON_LOAD_OPTION_DESC', 'pt_BR', "Mostra a camada de rendimentos dos terrenos ao carregar o jogo. As camadas ainda podem ser alternadas com os filtros do minimapa ou atalhos de teclado."),
			('LOC_MOD_CSL_SHOW_YIELDS_ON_LOAD_OPTION_DESC', 'ru_RU', "Показывать слой доходности клеток при загрузке игры. Слои можно переключать с помощью фильтров мини-карты или горячих клавиш."),
			('LOC_MOD_CSL_SHOW_YIELDS_ON_LOAD_OPTION_DESC', 'zh_Hans_CN', "游戏加载时显示单元格收益层。仍可使用小地图过滤器或快捷键切换图层。"),
			('LOC_MOD_CSL_SHOW_YIELDS_ON_LOAD_OPTION_DESC', 'zh_Hant_HK', "遊戲加載時顯示單元格收益層。仍可使用小地圖篩選器或快捷鍵切換圖層。");
--========================================================================================================================
--========================================================================================================================
